@echo on

set TASM_PATH=C:\TASM\TASM.EXE
set TLINK_PATH=C:\TASM\TLINK.EXE

set PROJECT_ASM_PATH=C:\TASM\LABRAB2.ASM
set PROJECT_OBJ_PATH=C:\TASM\LABRAB2.OBJ

set IOPROC_OBJ_PATH=C:\TASM\IOPROC.OBJ

%TASM_PATH% %PROJECT_ASM_PATH%

%TLINK_PATH% %PROJECT_OBJ_PATH% + %IOPROC_OBJ_PATH%



echo finish


